### ISSUE TITLE
Remote admin interface on google compute engine

### ISSUE THREAD

**Issue by stellanhaglund** [rethinkdb/rethinkdb-dockerfiles#25]
Hi I was just wondering if you have any idea how I would be able to access the interface if docker is runned on an compute engine instance?

I tried this.
```
ssh -fNTL localhost:8080:$(gcloud compute ssh docker-rdb --zone europe-west1-b "docker inspect --format '{{ .NetworkSettings.IPAddress }}' some-rethink"):8080 remote
```

**Comment by danielmewes** [comment]
I'm not sure. Maybe @dalanmiller has an idea?

I would expect something like your `ssh` tunnel to do the job.

**Comment by stuartpb** [comment]
Are you replacing `some-rethink` with the name of your container on the instance?

**Comment by stellanhaglund** [comment]
Its named some-rethink, i started the container using the example command
from the readme

torsdag 10 mars 2016 skrev Stuart P. Bentley <notifications@github.com>:

**Comment by stuartpb** [comment]
What about `remote`? Are you replacing that with the address?

**Comment by stellanhaglund** [comment]
You mean the remote at the end of the command?

I tried changing that to things like hostname of container or instance, IP
to instance or container but the error always say, something similar to
SSH, could not resolve hostname

torsdag 10 mars 2016 skrev Stuart P. Bentley <notifications@github.com>:

**Comment by stuartpb** [comment]
It's weird that it'd be saying "could not resolve hostname" about an IP address. Did you inspect the output of `gcloud compute ssh docker-rdb --zone europe-west1-b "docker inspect --format '{{ .NetworkSettings.IPAddress }}' some-rethink"`?

**Comment by stellanhaglund** [comment]
No I wanted to but i wasnt sure how to do that! :)

torsdag 10 mars 2016 skrev Stuart P. Bentley <notifications@github.com>:

**Comment by stuartpb** [comment]
run `gcloud compute ssh docker-rdb --zone europe-west1-b "docker inspect --format '{{ .NetworkSettings.IPAddress }}' some-rethink"`

**Comment by stellanhaglund** [comment]
I will, i will let you know what the result is.

Thanks!!

torsdag 10 mars 2016 skrev Stuart P. Bentley <notifications@github.com>:

**Comment by stellanhaglund** [comment]
it gave me 172.17.0.2

2016-03-10 0:16 GMT+01:00 Stellan Haglund <sh@idly.se>:

**Comment by stellanhaglund** [comment]
this command ssh -fNTL localhost:8080:$(gcloud compute ssh docker-rdb
--zone europe-west1-b "docker inspect --format '{{
.NetworkSettings.IPAddress }}' some-rethink"):8080 172.17.0.2

gives me this error instead ssh: connect to host 172.17.0.2 port 22:
Connection refused

2016-03-10 7:52 GMT+01:00 Stellan Haglund <sh@idly.se>:

**Comment by stuartpb** [comment]
172.17.0.2 is the address of the container *inside the instance*. It's not routable to the general internet. The address you want the outer `ssh` to be targeted at is *the address of the instance*.

If we're sticking with the `gcloud compute ssh` [wrapper](https://cloud.google.com/sdk/gcloud/reference/compute/ssh), that command would be:

`gcloud compute ssh docker-rdb
--zone europe-west1-b -- -fNTL localhost:8080:$(gcloud compute ssh docker-rdb
--zone europe-west1-b "docker inspect --format '{{
.NetworkSettings.IPAddress }}' some-rethink"):8080`

**Comment by stellanhaglund** [comment]
Yes now it works! thank you!!

2016-03-10 11:08 GMT+01:00 Stuart P. Bentley <notifications@github.com>:

**Comment by danielmewes** [comment]
Maybe we should document this somewhere if it isn't already documented...

@stellanhaglund Did you come up with your original `ssh` command yourself or did you find that in some documentation?

**Comment by stellanhaglund** [comment]
The most part is from the docker readme i just changed to the gcloud part
instead of the regular ssh.

torsdag 10 mars 2016 skrev Daniel Mewes <notifications@github.com>:

**Comment by stuartpb** [comment]
I'm okay leaving the README so that it only describes the mechanism for constructing the tunnel with general SSH. If somebody wants to convert that to a wrapper like `gcloud compute ssh` (or some other provider's toolbelt, like AWS or Azure), they can work out the appropriate translation for themselves - maybe they'll just do a Google search and find this issue that says how to do it (with `gcloud compute ssh`, you separate the `gcloud` options from the `ssh` tunneling options with a `--`, as demonstrated [above](https://github.com/rethinkdb/rethinkdb-dockerfiles/issues/25#issuecomment-194770459)).
