### ISSUE TITLE
Update to 2.3.1

### ISSUE THREAD

**Issue by lbguilherme** [rethinkdb/rethinkdb-dockerfiles#28]
The web interface is already warning about the new release, but I can't update because my deployment is Docker based and it uses this image.

Please release an update for 2.3.1

**Comment by danielmewes** [comment]
@dalanmiller is on it.

**Comment by dalanmiller** [comment]
@lbguilherme is there a good way we can notify you about updates? Are you a part of our community Slack org? I was thinking of starting a #docker channel where I can automate the availability of new releases there.

**Comment by lbguilherme** [comment]
@dalanmiller Thanks for the quick update!

I am part of the slack community but I don't really follow it, it gets too noisy quickly. I usually watch the GitHub repository for popular issues and for releases, this is where I read about the 2.3.1 release, few hours after release.

I considered asking on slack before opening this issue, but didn't find a suitable channel (and this is more like a task than a question, so makes more sense to be here). A docker channel could indeed be useful for releases and docker configuration questions.
