### ISSUE TITLE
Cache size/swap memory

### ISSUE THREAD

**Issue by neurotech** [rethinkdb/rethinkdb-dockerfiles#29]
Hi - I am using `2.3.2 jessie` (https://github.com/rethinkdb/rethinkdb-dockerfiles/blob/master/jessie/2.3.2/Dockerfile) and I get this issue on my admin console sometimes:

```
Some RethinkDB data on this server has been placed into swap memory in the past hour. This may impact performance.
```

My container has been run with the `--memory "512M"` flag, if that helps.

Also, the container's log have this entry:

```
warn: Cache size does not leave much memory for server and query overhead (available memory: 794 MB).
```

How can I resolve this?

**Comment by danielmewes** [comment]
For other readers: Some ideas that were mentioned at rethinkdb.slack.com:
* Reduce the cache size through `--cache-size 32` to reduce memory usage.
* Try `--memory 512MB --memory-swap 0` to disable swap. However it could make RethinkDB crash when running out of memory.

**Comment by daveisfera** [comment]
When running running the official docker image of 2.3.5 with `--memory=4G --memory-swap=0` I still see this message. Anything I can do to help diagnose the cause of this issue?

**Comment by stuartpb** [comment]
https://github.com/rethinkdb/rethinkdb/issues?q=is%3Aissue+memory
