### ISSUE TITLE
Link to other repo on Dockerhub

### ISSUE THREAD

**Issue by MarkHerhold** [rethinkdb/rethinkdb-dockerfiles#31]
This page https://hub.docker.com/_/rethinkdb/ has a link to create a "GitHub Issue" at the bottom of the page. The link points to `https://github.com/stuartpb/rethinkdb-dockerfiles/issues`

I suspect that it should point to this repo instead.

**Comment by stuartpb** [comment]
See docker-library/docs#604

**Comment by MarkHerhold** [comment]
Thanks, closing this issue.
