### ISSUE TITLE
Rethinkdb:2.2.5 with Docker for Mac

### ISSUE THREAD

**Issue by ambodi** [rethinkdb/rethinkdb-dockerfiles#33]
When running rethinkdb:2.2.5 image with Docker Version 1.12.0-beta22 (build: 11222) for Mac, very rapidly all the CPU resources are being used:

![screen shot 2016-08-16 at 17 08 53](https://cloud.githubusercontent.com/assets/6009583/17704298/f46dd0fc-63d4-11e6-8c2e-f992c6f47763.png)

I wonder why is that the case. It's happening with the stable version too, so I don't think its related because of the beta!

**Comment by yosifkit** [comment]
This is not limited to RethinkDB, and is a "Docker for Mac" issue: 

 - https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/2
 - https://forums.docker.com/t/com-docker-hyperkit-up-cpu-to-340/13057/23

**Comment by ambodi** [comment]
@yosifikit awesome! Thanks for your help!
