### ISSUE TITLE
Docker 1.12 Healthchecks support

### ISSUE THREAD

**Issue by royeectu** [rethinkdb/rethinkdb-dockerfiles#34]
Hi,

Docker 1.12 supports healthchecks out of the box.
In order to use it you need to add the HEALTHCHECK directive to the Dockerfile.
You can read about it here: [healthchecks](https://docs.docker.com/engine/reference/builder/#/healthcheck)
Could you please add it to the Dockerfile?

**Comment by royeectu** [comment]
Anyone?

**Comment by gjuchault** [comment]
Could be nice !

**Comment by stuartpb** [comment]
Closing per explanation in https://github.com/rethinkdb/rethinkdb-dockerfiles/pull/36#issuecomment-326398363.
