### ISSUE TITLE
ENV Variables for clustering

### ISSUE THREAD

**Issue by qrpike** [rethinkdb/rethinkdb-dockerfiles#35]
I don't see in the docs or the Dockerfile itself where it's possible to define how/what cluster it should try to connect to.

I guess we could override the CMD with the params, but it would be nice to just define environment variables to specify the cluster IP, etc.

**Comment by stuartpb** [comment]
> I guess we could override the CMD with the params

That's how all RethinkDB configuration happens. If you want to add a more-opinionated configuration layer, you can put it in your own derivative image with a Dockerfile that starts with `FROM rethinkdb`.
