### ISSUE TITLE
update Dockerhub repo to include 2.3.6

### ISSUE THREAD

**Issue by lucidfrontier45** [rethinkdb/rethinkdb-dockerfiles#38]
Hi. I'm super happy for the release of 2.3.6.

Now the official docker image's latest tag is still set to 2.3.5.
https://hub.docker.com/_/rethinkdb/
Can you update it to 2.3.6. (add 2.3.6 tag and set 2, 2.3, latest to 2.3.6)

Thank you.

**Comment by lucidfrontier45** [comment]
also see https://github.com/docker-library/official-images/issues/3252#issuecomment-318769845

**Comment by lucidfrontier45** [comment]
The document is also needed to update.
https://github.com/docker-library/docs/tree/master/rethinkdb

**Comment by reederz** [comment]
Any progress on this? Would love to see the new version up on docker hub :)

**Comment by Vanuan** [comment]
Unfortunately, docker-library maintainers need a confirmation from one of rethinkdb maintainers.
And as far as I can see, all rethinkdb maintainers had left.

@AtnNn @coffeemug @danielmewes @mglukhovsky @mlucy @neumino @timmaxw @Tryneus @VeXocide anybody willing to tell a word on docker-library/official-images#3332 ?

**Comment by lucidfrontier45** [comment]
rethinkdb:2.3.6 image was released
https://hub.docker.com/_/rethinkdb/
