### ISSUE TITLE
2.4.2 tag is 2.4.1 in container

### ISSUE THREAD

**Issue by metal3d** [rethinkdb/rethinkdb-dockerfiles#63]
**Describe the bug**
Pulling `rethinkdb:2.4.2` and opening the UI - version alert appears and the version is not set to 2.4.2

**To Reproduce**
1. `docker run --rm -it -p 8080:8080 rethinkdb:2.4.2`
2. Open http://localhost:8080
4. Press the "parameter" button and see the version

**Expected behavior**
Inside the UI, the update alert should not appear and the version should be set to 2.4.2

**Screenshots**
![image](https://user-images.githubusercontent.com/100080/178267604-c86ac842-2604-488e-9401-9ad88d4b26f6.png)

**System info**
 - OS: Linux Fedora 35 with podman and docker
 - RethinkDB Version: 2.4.2

**Comment by metal3d** [comment]
Hello,
No news ?

**Comment by srh** [comment]
This is a bug in RethinkDB 2.4.2's web UI.

It was tracked in https://github.com/rethinkdb/rethinkdb/issues/7072 .

It is fixed in RethinkDB 2.4.3.

Is there a dockerfiles update for 2.4.3?

**Comment by mariushosting** [comment]
@gabor-boros 
Any news on this?

**Comment by mariushosting** [comment]
> --version

No Docker version for 2.4.3 since 4 months

**Comment by gabor-boros** [comment]
I'll be back on the 30th of June to take care of this

**Comment by gabor-boros** [comment]
I didn't forget about it, but had no time yet to fix it. Will do next week.

**Comment by srh** [comment]
@gabor-boros I've merged 2.4.3 images and have https://github.com/docker-library/official-images/pull/15893 up now.
