### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by tianon** [rethinkdb/rethinkdb-dockerfiles#67]
:wave: attempts to rebuild https://hub.docker.com/_/rethinkdb for recent base image updates are now failing with 502 server errors (https://github.com/rethinkdb/rethinkdb/issues/7153?)

This should be reproducible with a plain `docker build https://github.com/rethinkdb/rethinkdb-dockerfiles.git#48876a66c3be922c6b01c436bf78d662e53bceef:bookworm/2.4.4`

**Comment by gabor-boros** [comment]
Hey @tianon, the download server was down. Now it is back online, so every build that failed before should build again. https://github.com/rethinkdb/rethinkdb/issues/7153#issuecomment-2297129100

**Comment by tianon** [comment]
Nice, can confirm, thank you!!
